[package]
name = "wgpu_app"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "0.19"
winit = "0.29"
anyhow = "*"
bytemuck = { version = "*", features = ["derive"] }
pollster = "*"

[[example]]
name = "texture_from_cpu"
path = "Examples/texture_from_cpu.rs"